name: Generate Snake Animation for Profile

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: # <--- INI BAGIAN YANG DITAMBAHKAN
      contents: write # <--- INI PEMBERIAN IZIN
    steps:
      - uses: actions/checkout@v3
      - uses: platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Bobbb00
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-pacman.svg?palette=pacman
          
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
