name: Generate Snake Animation for Profile

on:
  schedule:
    # Menjalankan setiap 12 jam (Anda bisa mengubahnya jika mau)
    - cron: "0 */12 * * *"
  workflow_dispatch: # Memungkinkan Anda menjalankan secara manual dari tab Actions

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Bobbb00  # <--- PASTIKAN INI ADALAH USERNAME GITHUB ANDA
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark # Untuk tema gelap
            dist/github-snake-pacman.svg?palette=pacman # Ini tema Pac-Man!

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # Branch 'output' akan menyimpan file SVG
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token otomatis GitHub
